name: directory list
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Append directory tree to README
        run: |
          sudo apt-get install tree
          sudo rm -rf README.md
          touch README.md
          git add README.md
          echo "# study notes \n  ## My personal study organization note     " > README.md
          tree --dirsfirst --noreport -I README.md | sed 's/^/    /' >> README.md
      - name: push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update README with directory list"
          git push origin main
